'use strict';
let csrf='',offset=0,total=0;const limit=30;const $=id=>document.getElementById(id);
const size=n=>{const units=['B','KiB','MiB','GiB','TiB'];let i=0;while(n>=1024&&i<4){n/=1024;i++}return `${n.toFixed(i?1:0)} ${units[i]}`};
async function api(path,options={}){options.headers={...options.headers,'X-CSRF-Token':csrf};const r=await fetch('/api/v1/'+path,options);const b=await r.json();if(!r.ok){if(r.status===401)showLogin();throw Error(b.error||'Request failed')}return b}
function error(e){$('global-error').textContent=e.message;$('global-error').hidden=false}
function showLogin(){$('app').hidden=true;$('login-view').hidden=false}
async function showApp(){$('login-view').hidden=true;$('app').hidden=false;await refresh()}
async function refresh(){try{const s=await api('status');$('stat-packages').textContent=s.packages.toLocaleString();$('stat-bytes').textContent=size(s.bytes);$('version').textContent='Version '+s.version;await inventory()}catch(e){error(e)}}
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el}
async function inventory(){const id=$('search').value.trim().toLowerCase();const d=await api(`extensions?limit=${limit}&offset=${offset}&id=${encodeURIComponent(id)}`);total=d.total;$('packages').replaceChildren();$('empty').hidden=total!==0;
for(const p of d.packages){const tr=node('tr');const name=node('td');name.append(node('span',p.id,'package-id'),node('span',p.displayName||'Extension package','package-name'));tr.append(name);const version=node('td',p.version);if(p.prerelease)version.append(node('span',' prerelease','package-name'));tr.append(version,node('td',p.platform),node('td',size(p.size)));const status=node('td');status.append(node('span',p.status,p.status==='stored'?'chip':'chip warn'));tr.append(status);const actions=node('td');const info=node('button','Details','quiet');info.addEventListener('click',()=>{$('detail-title').textContent=p.id;$('detail-body').textContent=JSON.stringify(p,null,2);$('detail').showModal()});const download=node('a','↓');download.setAttribute('aria-label','Download '+p.id+' '+p.version);download.href='/api/v1/packages/download?key='+encodeURIComponent(`${p.id}@${p.version}@${p.platform}`);actions.append(info,download);tr.append(actions);$('packages').append(tr)}
$('page-info').textContent=total?`${offset+1}–${Math.min(offset+limit,total)} of ${total} packages`:'No packages yet';$('prev').disabled=offset===0;$('next').disabled=offset+limit>=total}
async function view(name){$('global-error').hidden=true;document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!=='view-'+name);document.querySelectorAll('.nav').forEach(el=>el.classList.toggle('active',el.dataset.view===name));$('page-title').textContent={inventory:'Extension inventory',upload:'Upload packages',runs:'Sync history',audit:'Activity log'}[name];try{if(name==='inventory')await refresh();if(name==='runs'){const runs=await api('sync-runs');$('runs').replaceChildren();if(!runs.length)$('runs').append(node('div','No sync reports yet. Run marketplace-sync to start your first collection.','empty'));for(const r of runs){const d=node('details',undefined,'history');d.append(node('summary',`${r.status} · ${r.finished||r.started} · ${r.stored||0} uploaded / ${r.skipped||0} existing / ${r.failed||0} failed`),node('pre',JSON.stringify(r,null,2)));$('runs').append(d)}}if(name==='audit'){const events=await api('audit-events');$('audit').replaceChildren();for(const e of events)$('audit').append(node('div',`${e.at}  ·  ${e.actor}  ·  ${e.action}  ${e.detail}`,'history'));if(!events.length)$('audit').append(node('p','No recorded events.','muted'))}}catch(e){error(e)}}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();$('login-error').textContent='';try{const b=await api('login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('password').value})});csrf=b.csrfToken;$('password').value='';await showApp()}catch(err){$('login-error').textContent=err.message}});
$('logout').addEventListener('click',async()=>{try{await api('logout',{method:'POST'});csrf='';showLogin()}catch(e){error(e)}});
document.querySelectorAll('.nav').forEach(el=>el.addEventListener('click',()=>view(el.dataset.view)));
$('empty-upload').addEventListener('click',()=>view('upload'));$('close-detail').addEventListener('click',()=>$('detail').close());
$('search-form').addEventListener('submit',e=>{e.preventDefault();offset=0;inventory().catch(error)});$('clear').addEventListener('click',()=>{$('search').value='';offset=0;inventory().catch(error)});$('refresh').addEventListener('click',refresh);$('prev').addEventListener('click',()=>{offset=Math.max(0,offset-limit);inventory().catch(error)});$('next').addEventListener('click',()=>{offset+=limit;inventory().catch(error)});
function upload(file,progress){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST','/api/v1/extensions');x.setRequestHeader('Content-Type','application/octet-stream');x.setRequestHeader('X-CSRF-Token',csrf);x.upload.onprogress=e=>{if(e.lengthComputable)progress.value=e.loaded/e.total*100};x.onerror=()=>reject(Error('Connection lost. Retry safely; a completed upload will be detected.'));x.onload=()=>{let b;try{b=JSON.parse(x.responseText)}catch{reject(Error('Unexpected server response'));return}if(x.status>=200&&x.status<300)resolve(b);else reject(Error(b.error||'Upload rejected'))};x.send(file)})}
$('upload-form').addEventListener('submit',async e=>{e.preventDefault();$('upload-submit').disabled=true;for(const file of $('files').files){const box=node('div',undefined,'result');const title=node('strong',file.name);const progress=node('progress');progress.max=100;progress.value=0;const status=node('p','Uploading…');box.append(title,progress,status);$('upload-results').append(box);try{const r=await upload(file,progress);progress.value=100;status.textContent=`${r.duplicate?'Already stored':'Stored'}: ${r.package.id} ${r.package.version} · ${r.package.platform}`}catch(err){status.textContent=err.message;status.className='error'}}$('upload-submit').disabled=false;refresh()});
(async()=>{try{const b=await api('me');csrf=b.csrfToken;await showApp()}catch{showLogin()}})();
