'use strict';
let csrf='',offset=0,total=0,scanTimer,searchTimer,loads=0;const limit=30;const $=id=>document.getElementById(id);
const size=n=>{const units=['B','KiB','MiB','GiB','TiB'];let i=0;while(n>=1024&&i<4){n/=1024;i++}return `${n.toFixed(i?1:0)} ${units[i]}`};
const count=(n,word)=>`${n.toLocaleString()} ${word}${n===1?'':'s'}`;const day=s=>s?new Date(s).toLocaleDateString():'—';
async function api(path,options={}){options.headers={...options.headers,'X-CSRF-Token':csrf};const r=await fetch('/api/v1/'+path,options);const b=await r.json();if(!r.ok){if(r.status===401)showLogin();throw Error(b.error||'Request failed')}return b}
function error(e){$('global-error').textContent=e.message;$('global-error').hidden=false}
function showLogin(){$('app').hidden=true;$('login-view').hidden=false}
async function showApp(){$('login-view').hidden=true;$('app').hidden=false;await refresh()}
async function refresh(){try{const s=await api('status');for(const k of ['extensions','versions','packages','attention'])$('stat-'+k).textContent=s[k].toLocaleString();$('stat-bytes').textContent=size(s.bytes);$('stat-attention-card').classList.toggle('warn',s.attention>0);$('version').textContent='Version '+s.version;if(scanning(s.inventory))return;if($('extension-view').hidden)await catalog();else await extension($('ext-id').textContent)}catch(e){error(e)}}
function scanning(scan){clearTimeout(scanTimer);$('scan-notice').hidden=scan.state!=='scanning';if(scan.state==='failed')throw Error(`The extension folder scan failed: ${scan.error}. Fix the cause, then reconcile storage.`);if(scan.state!=='scanning')return false;$('scan-notice').textContent=`Verifying the extension folder after a restart: ${scan.scanned.toLocaleString()} of ${scan.total.toLocaleString()} packages checked. The inventory, uploads, and downloads open when it finishes.`;scanTimer=setTimeout(refresh,5000);return true}
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el}
function statusCell(counts){const cell=node('td');const issues=Object.entries(counts).filter(([k])=>k!=='stored');if(!issues.length)cell.append(node('span','All stored','chip'));for(const [k,n] of issues)cell.append(node('span',`${n} ${k}`,'chip warn'));return cell}
function showCatalog(){$('extension-view').hidden=true;$('catalog-view').hidden=false}
async function catalog(){const load=++loads;const q=new URLSearchParams({limit,offset,sort:$('sort').value,q:$('search').value.trim()});if($('attention-only').checked)q.set('attention','true');const d=await api('catalog?'+q);if(load!==loads)return;total=d.total;const filtered=q.get('q')!==''||q.has('attention');$('extensions').replaceChildren();$('empty').hidden=total!==0||filtered;$('no-match').hidden=total!==0||!filtered;
for(const x of d.extensions){const tr=node('tr',undefined,'clickable');tr.addEventListener('click',()=>extension(x.id).catch(error));const name=node('td');const open=node('button',x.id,'link package-id');open.setAttribute('aria-label','Show versions of '+x.id);name.append(open,node('span',x.displayName||'Extension package','package-name'));const platforms=node('td');const chip=node('span',x.platforms.length===1?x.platforms[0]:count(x.platforms.length,'platform'),'chip plain');chip.title=x.platforms.join(', ');platforms.append(chip);const go=node('td','›','chevron');go.setAttribute('aria-hidden','true');tr.append(name,node('td',x.latestVersion),node('td',x.versions.toLocaleString()),platforms,node('td',x.packages.toLocaleString()),node('td',size(x.bytes)),statusCell(x.statusCounts),go);$('extensions').append(tr)}
$('page-info').textContent=total?`${offset+1}–${Math.min(offset+limit,total)} of ${count(total,'extension')}`:'';$('prev').disabled=offset===0;$('next').disabled=offset+limit>=total}
async function extension(id){const d=await api('catalog/'+encodeURIComponent(id));const x=d.extension;$('catalog-view').hidden=true;$('extension-view').hidden=false;$('ext-id').textContent=x.id;$('ext-name').textContent=x.displayName||x.id;$('ext-summary').textContent=`Latest ${x.latestVersion} · ${count(x.versions,'version')} · ${count(x.platforms.length,'platform')} · ${count(x.packages,'package file')} · ${size(x.bytes)}`;$('versions').replaceChildren();
for(const v of d.versions){const tr=node('tr');const version=node('td');version.append(node('span',v.version,'package-id'));if(v.version===x.latestVersion)version.append(node('span','latest','chip'));if(v.prerelease)version.append(node('span','prerelease','chip plain'));const platforms=node('td',undefined,'wrap');const counts={};for(const p of v.packages){counts[p.status]=(counts[p.status]||0)+1;const b=node('button',p.platform,p.status==='stored'?'chip plain':'chip warn');b.title=p.status==='stored'?'Details and download':p.status;b.addEventListener('click',()=>details(p));platforms.append(b)}tr.append(version,platforms,node('td',size(v.bytes)),node('td',day(v.storedAt)),statusCell(counts));$('versions').append(tr)}window.scrollTo(0,0)}
function details(p){$('detail-title').textContent=`${p.id} ${p.version} · ${p.platform}`;$('detail-body').textContent=JSON.stringify(p,null,2);const a=$('detail-download');a.hidden=p.status!=='stored';a.href='/api/v1/packages/download?key='+encodeURIComponent(`${p.id}@${p.version}@${p.platform}`);$('detail').showModal()}
async function view(name){$('global-error').hidden=true;document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!=='view-'+name);document.querySelectorAll('.nav').forEach(el=>el.classList.toggle('active',el.dataset.view===name));$('page-title').textContent={inventory:'Extension inventory',upload:'Upload packages',runs:'Sync history',audit:'Activity log'}[name];try{if(name==='inventory'){showCatalog();await refresh()}if(name==='runs'){const runs=await api('sync-runs');$('runs').replaceChildren();if(!runs.length)$('runs').append(node('div','No sync reports yet. Run marketplace-sync to start your first collection.','empty'));for(const r of runs){const d=node('details',undefined,'history');d.append(node('summary',`${r.status} · ${r.finished||r.started} · ${r.stored||0} uploaded / ${r.skipped||0} existing / ${r.failed||0} failed`),node('pre',JSON.stringify(r,null,2)));$('runs').append(d)}}if(name==='audit'){const events=await api('audit-events');$('audit').replaceChildren();for(const e of events)$('audit').append(node('div',`${e.at}  ·  ${e.actor}  ·  ${e.action}  ${e.detail}`,'history'));if(!events.length)$('audit').append(node('p','No recorded events.','muted'))}}catch(e){error(e)}}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();$('login-error').textContent='';try{const b=await api('login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('password').value})});csrf=b.csrfToken;$('password').value='';await showApp()}catch(err){$('login-error').textContent=err.message}});
$('logout').addEventListener('click',async()=>{try{await api('logout',{method:'POST'});csrf='';showLogin()}catch(e){error(e)}});
document.querySelectorAll('.nav').forEach(el=>el.addEventListener('click',()=>view(el.dataset.view)));
$('empty-upload').addEventListener('click',()=>view('upload'));$('close-detail').addEventListener('click',()=>$('detail').close());
const reload=()=>{clearTimeout(searchTimer);offset=0;catalog().catch(error)};
$('search-form').addEventListener('submit',e=>{e.preventDefault();reload()});$('search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(reload,300)});$('sort').addEventListener('change',reload);$('attention-only').addEventListener('change',reload);$('clear').addEventListener('click',()=>{$('search').value='';$('sort').value='name';$('attention-only').checked=false;reload()});$('refresh').addEventListener('click',refresh);$('prev').addEventListener('click',()=>{offset=Math.max(0,offset-limit);catalog().catch(error)});$('next').addEventListener('click',()=>{offset+=limit;catalog().catch(error)});
$('back').addEventListener('click',()=>{showCatalog();catalog().catch(error)});$('stat-attention-card').addEventListener('click',()=>{$('attention-only').checked=true;offset=0;view('inventory')});
function upload(file,progress){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST','/api/v1/extensions');x.setRequestHeader('Content-Type','application/octet-stream');x.setRequestHeader('X-CSRF-Token',csrf);x.upload.onprogress=e=>{if(e.lengthComputable)progress.value=e.loaded/e.total*100};x.onerror=()=>reject(Error('Connection lost. Retry safely; a completed upload will be detected.'));x.onload=()=>{let b;try{b=JSON.parse(x.responseText)}catch{reject(Error('Unexpected server response'));return}if(x.status>=200&&x.status<300)resolve(b);else reject(Error(b.error||'Upload rejected'))};x.send(file)})}
$('upload-form').addEventListener('submit',async e=>{e.preventDefault();$('upload-submit').disabled=true;for(const file of $('files').files){const box=node('div',undefined,'result');const title=node('strong',file.name);const progress=node('progress');progress.max=100;progress.value=0;const status=node('p','Uploading…');box.append(title,progress,status);$('upload-results').append(box);try{const r=await upload(file,progress);progress.value=100;status.textContent=`${r.duplicate?'Already stored':'Stored'}: ${r.package.id} ${r.package.version} · ${r.package.platform}`}catch(err){status.textContent=err.message;status.className='error'}}$('upload-submit').disabled=false;refresh()});
(async()=>{try{const b=await api('me');csrf=b.csrfToken;await showApp()}catch{showLogin()}})();
